### ISSUE TITLE
Memory usage - different values reported by SwiftMetrics and Activity Monitor (macOS)

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/SwiftMetrics#2] opened 2017-01-26 11:13 UTC
Raised from 

https://github.com/IBM-Swift/SwiftMetrics/issues/50

**Comment by rolivieri** [comment] 2017-01-26 19:32
@hhellyer, @tobespc Thanks for the info. I added those additional columns and I see now that the value reported under "Real Memory" in Activity Monitor matches the value reported by SwiftMetrics. I am then assuming the intention is to report [via SwiftMetrics] the "Real Memory" value since it includes shared memory. Is this correct? I am guessing this is also what has been done for the other runtimes. If so, then it sounds like it is working as designed. Can you guys confirm?

**Comment by rolivieri** [comment] 2017-01-26 19:33
@thesounddefense - Keeping you in the loop; see above.

**Comment by tobespc** [comment] 2017-01-27 09:04
@rolivieri so that is then intention right now, however, if you would like the value to be sent without including shared memory we would require a larger change as we don't collect that right now.  We can do it, it would just be put as a lower priority behind the rest of the work for swiftmetrics.   

So, my question is how critical to you is have the memory value without including shared memory ?

**Comment by rolivieri** [comment] 2017-01-27 19:56
@tobespc As of now, I don't have a use case for collecting the value without shared memory. If we are taking for Swift the same approach that was taken for the other runtimes (node, java, etc.) then I'd say we are good for now.

**Comment by stalleyj** [comment] 2017-01-30 11:20
I'm going to close this issue as we are providing the same information across all runtimes. I've also raised an enhancement to implement the applicationPrivateSize on macOS https://github.com/RuntimeTools/SwiftMetrics/issues/15

**Closed as completed by stalleyj** 2017-01-30 11:20 UTC
Labels: bug
